eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/    
server:
  port: 9999
spring:
  application:
    name: SHOPPING-SERVICE
