eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/    
server:
  port: 8888
spring:
  application:
    name: PAYMENT-SERVICE
